### ISSUE TITLE
Question about training with small dataset entries

### ISSUE THREAD

**Issue by ProtoxiDe22** [nshepperd/gpt-2#25]
hello, as the title suggest, i'm trying to train the model on a set of very small texts (these are actually messages from a chat, just so you can understand the type of content), and i'm running in two main problems. first (not sure if directly related to the size of the entries) i generated my dataset like so 
`message
<|endoftext|>
message`
this way, a good part of my dataset, is actually made up of `<|endoftext|>`, i would have expected that since this is a delimiter, it would be ignored by the training, but it seems this is not the case since my samples are full of it
```
======== SAMPLE 1 ========
* <|endoftext|> 
ma in realtà lei è poco dai
 <|endoftext|> 
che fine ha fatto anche quell'altro non farei mai nascosti
 <|endoftext|> 
eh ma cosa
 <|endoftext|> 
```

also, (i might be wrong here, since i don't fully understand how the model works) i would have expected that since i;m training with very short texts, which are about 12-15 words long, the generated samples would be of a similar size, instead, i get full blown 50 lines samples (excluding the ` <|endoftext|>`), is that a "limitation of the model"? are the separators not working? or is there a way to force shorter samples?
i should also note that as of now, on the last dataset i'm training, i'm about 70 000 steps maybe it is too few? also as you can see from the sample, i'm actually not training english but italian, could that be the cause?

**Comment by HansBambel** [comment]
When generating samples you can

**Comment by HansBambel** [comment]
When using the `generate_unconditioned_samples.py` or the other sampling files you can set a limit to the number of tokens you want to have using `--length <number of tokens>`. By default this is set to the value of `n_ctx` in the `hparams.json` --> 1024 for the 117M/124M model.

The <|endoftext|> shows that the message is done, but it still generates the previously set amount of tokens. Resulting in multiple messages.

**Comment by ProtoxiDe22** [comment]
i think i got my answers here, thanks
