### ISSUE TITLE
Unicode characters each considered as a token

### ISSUE THREAD

**Issue by Masum06** [nshepperd/gpt-2#34]
Hi,

I have retrained the 117M parameter model with 6GB Bengali text dataset. Setting the **_'--length'_** parameter to 100 in interactive conditional sample generation is supposed to create 100 tokens, but in my case it is generating 100 characters. This makes me believe that for unicode characters the model is considering each character as a token. How do I make it consider each word as a token?

Thanks in advance.

**Comment by Masum06** [comment]
@nshepperd could you please take a look?

**Comment by nshepperd** [comment]
The tokenizer for gpt-2 was trained on a dataset which likely did not include much Bengali text. This is why it is not aware of Bengali word units. If you want to get good results on this sort of text, you'll need to generate a new vocab.bpe for your dataset. I don't know much about that process, but a good starting point would be to read the links from https://github.com/openai/gpt-2/issues/104.
