### ISSUE TITLE
ModuleNotFoundError: No module named 'encoder'

### ISSUE THREAD

**Issue by shreesha345** [nshepperd/gpt-2#73]
$python encode.py training.txt trained.npz
`Traceback (most recent call last):
  File "encode.py", line 9, in <module>
    import encoder
ModuleNotFoundError: No module named 'encoder'
`
I am using python3.7.8
but I have installed the encoder.
please help me to fix it.

**Comment by bgujjal** [comment]
I am having the same issue and am too tired to try and fix it can someone please help me? I'll post a comment if I do eventually get around to fixing it

**Comment by Mart17** [comment]
This should work:
https://github.com/nshepperd/gpt-2/blob/finetuning/encode.py#L3

**Comment by Andrew-Pynch** [comment]
@shreesha345 @hypotheticalbarfi @Mart17 this does not work, has anyone managed to get this functioning?

**Comment by Mart17** [comment]
For me the solution was the line I posted: `PYTHONPATH=src ./encode.py directory-of-data path-to-encoded-output-file.npz`

**Comment by cwilliamjay** [comment]
I had to do this in the encode.py 
import src.encoder
from src.load_dataset import load_dataset
and then in main()
 enc = src.encoder.get_encoder(args.model_name, models_dir=args.models_dir)

this got me over this hump but now I'm stuck in the training part. need to do things similar but still stuck there
I

**Comment by shreesha345** [comment]
You should try it on google Colab it will work.
I tryed it on google Colab so you do it also.

**Comment by Sarutobification** [comment]
move the encoder.py and train.py to the src folder... this works for me dont know why
