### ISSUE TITLE
Cannot download the models

### ISSUE THREAD

**Issue by giorgiogiudice** [nshepperd/gpt-2#75]
Hello ya'll,

I am trying to download the models, but the files downloaded are all showing the same message

<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>

Am I missing something here?

**Comment by deepthi-skive** [comment]
I am having the same issue. The progress bars just show 0%. Did you manage to solve the issue ?

**Comment by danhab99** [comment]
Same issue here.

Every file the script pulls contains this

```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>
```

**Comment by nshepperd** [comment]
They moved the models to a different hosting. I'll try to merge their changes from upstream which have the updated urls.

**Comment by nshepperd** [comment]
I merged upstream. Downloading models using `download_model.py` should work now.
