### ISSUE TITLE
File "encode.py", line 23

### ISSUE THREAD

**Issue by Jucamhc** [nshepperd/gpt-2#76]
(open-ai) D:\chatBox4\open-ai\gpt-2\src>python encode.py chat.txt chat.npz

Traceback (most recent call last):
  File "encode.py", line 31, in <module>
    main()
  File "encode.py", line 23, in main
    enc = encoder.get_encoder(args.model_name)
TypeError: get_encoder() missing 1 required positional argument: 'models_dir'

**Comment by nshepperd** [comment]
Pushed fix. Side effect from merging upstream changes which added models_dir flag.
