### ISSUE TITLE
ModuleNotFoundError: No module named 'Sampler'

### ISSUE THREAD

**Issue by haiitsstrawberry** [nshepperd/gpt-2#79]
there doesn't seem to be any module named Sampler, anywhere

**Comment by haiitsstrawberry** [comment]
figured it out

**Comment by sigmondkukla** [comment]
@manwhy Could you please say how you resolved this? I am currently having the same issue and I would love to know how to fix it.

**Comment by haiitsstrawberry** [comment]
i don't _entirely_ remember how i fixed it, it _might_ have been something to with differentiating between class names and file names, or it might have been something to do with circular file dependencies. not sure, since i don't have access to my old modified files anymore, but if i saw the exact error it might jog my memory up a little bit
